Allow benchmarks to run when there is no cupy.
glotzerlab/hoomd-benchmarks pull request #26
Opened 2022-07-15 13:43 UTC by joaander

## Description

Allow benchmarks to run when there is no cupy.

## Motivation and context

Users need to take extra steps to install cupy. Allow the benchmarks to complete without error when cupy is not installed. Those benchmarks that require cupy will not produce meaningful output.

## How has this been tested?

I tested this locally.

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk/ContributorAgreement.md).
- [x] My name is on the list of contributors (`CONTRIBUTORS.md`) in the pull request source branch.

2022-07-15 13:53 UTC, tommy-waltmann requested changes

2022-07-15 13:53 UTC, tommy-waltmann commented on hoomd_benchmarks/common.py
> +            return 0
Can a short comment be added to clarify the circumstances under which a simulation's TPS might be 0?

2022-07-15 15:03 UTC, joaander commented on hoomd_benchmarks/common.py
> +            return 0
Done.

2022-07-15 15:06 UTC, tommy-waltmann approved these changes

2022-07-31 02:10 UTC, shihkual approved these changes
Looks good to me.

2022-08-01 14:47 UTC, merged